apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: howest-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.4
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-secret
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: database-storage
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: pvc-database
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb
  namespace: howest-k8s-demo
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
