apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-api
  namespace: howest-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
