replicaCount: 1

image:
  repository: ghcr.io/nathansegers/fastapi-intro
  tag: v1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name:

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

podSecurityContext: {}
securityContext: {}
