apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: howest-k8s-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: nathansegers/01-fastapi-2022
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mariadb-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-fastapi
  namespace: howest-k8s-demo
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
