server {
    listen 80;
    server_name _;

    resolver 127.0.0.11 valid=5s;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $upstream http://api;
        rewrite ^/api/(.*) /$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /state/ {
        set $upstream http://state-api;
        rewrite ^/state/(.*) /$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
