// <auto-generated />
using Laptopreservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace examenadvancedsoftwarengineering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818082755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Laptopreservation.Models.Laptop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DisplaySize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("GpuBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("GpuType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTouchScreen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int>("NumCores")
                        .HasColumnType("int");

                    b.Property<int>("NumThreads")
                        .HasColumnType("int");

                    b.Property<string>("OS")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStorageCapacity")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryStorageType")
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessorBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessorTier")
                        .HasColumnType("longtext");

                    b.Property<int>("RamMemory")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryStorageCapacity")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryStorageType")
                        .HasColumnType("longtext");

                    b.Property<int>("YearOfWarranty")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Brand = "Macbook",
                            DisplaySize = 150.46m,
                            GpuBrand = "Apple Sillicon",
                            GpuType = "Multithreading",
                            IsTouchScreen = false,
                            Model = "M5",
                            NumCores = 12,
                            NumThreads = 36,
                            OS = "Catalina",
                            Price = 2005,
                            PrimaryStorageCapacity = 1000,
                            PrimaryStorageType = "Ssd",
                            ProcessorBrand = "AppleSilicon",
                            ProcessorTier = "Idk",
                            RamMemory = 38,
                            Rating = 100,
                            ResolutionHeight = 800,
                            ResolutionWidth = 200,
                            SecondaryStorageCapacity = 2000,
                            SecondaryStorageType = "HDD",
                            YearOfWarranty = 2030
                        },
                        new
                        {
                            ID = 2,
                            Brand = "Winodws",
                            DisplaySize = 150.46m,
                            GpuBrand = "Nvidia",
                            GpuType = "Multithreading",
                            IsTouchScreen = true,
                            Model = "M4",
                            NumCores = 12,
                            NumThreads = 36,
                            OS = "Windows",
                            Price = 2000000,
                            PrimaryStorageCapacity = 1000,
                            PrimaryStorageType = "Ssd",
                            ProcessorBrand = "Nvidia",
                            ProcessorTier = "Big",
                            RamMemory = 38,
                            Rating = 100,
                            ResolutionHeight = 800,
                            ResolutionWidth = 200,
                            SecondaryStorageCapacity = 2000,
                            SecondaryStorageType = "HDD",
                            YearOfWarranty = 2030
                        });
                });

            modelBuilder.Entity("Laptopreservation.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerAdress")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("longtext");

                    b.Property<decimal>("QuantityPerLaptop")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
