// <auto-generated />
using Laptopreservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace examenadvancedsoftwarengineering.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Laptopreservation.Models.Laptop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DisplaySize")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("GpuBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("GpuType")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTouchScreen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int>("NumCores")
                        .HasColumnType("int");

                    b.Property<int>("NumThreads")
                        .HasColumnType("int");

                    b.Property<string>("OS")
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStorageCapacity")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryStorageType")
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessorBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("ProcessorTier")
                        .HasColumnType("longtext");

                    b.Property<int>("RamMemory")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryStorageCapacity")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryStorageType")
                        .HasColumnType("longtext");

                    b.Property<int>("YearOfWarranty")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Brand = "Apple",
                            DisplaySize = 15.6m,
                            GpuBrand = "Apple Silicon",
                            GpuType = "Integrated",
                            IsTouchScreen = false,
                            Model = "MacBook Pro M5",
                            NumCores = 12,
                            NumThreads = 36,
                            OS = "macOS",
                            Price = 2005,
                            PrimaryStorageCapacity = 1000,
                            PrimaryStorageType = "SSD",
                            ProcessorBrand = "Apple Silicon",
                            ProcessorTier = "M5",
                            RamMemory = 38,
                            Rating = 100,
                            ResolutionHeight = 1600,
                            ResolutionWidth = 2560,
                            SecondaryStorageCapacity = 2000,
                            SecondaryStorageType = "HDD",
                            YearOfWarranty = 2030
                        },
                        new
                        {
                            ID = 2,
                            Brand = "Windows",
                            DisplaySize = 15.6m,
                            GpuBrand = "Nvidia",
                            GpuType = "Discrete",
                            IsTouchScreen = true,
                            Model = "X Series M4",
                            NumCores = 12,
                            NumThreads = 36,
                            OS = "Windows",
                            Price = 2000000,
                            PrimaryStorageCapacity = 1000,
                            PrimaryStorageType = "SSD",
                            ProcessorBrand = "Nvidia",
                            ProcessorTier = "High",
                            RamMemory = 38,
                            Rating = 100,
                            ResolutionHeight = 1080,
                            ResolutionWidth = 1920,
                            SecondaryStorageCapacity = 2000,
                            SecondaryStorageType = "HDD",
                            YearOfWarranty = 2030
                        });
                });

            modelBuilder.Entity("Laptopreservation.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ReservationID");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            CustomerAddress = "Boomstraat 30",
                            CustomerEmail = "jean-jacquesvandewalle@hotmail.com",
                            CustomerName = "Jean-Jacques",
                            CustomerPhone = "0456180394",
                            TotalPrice = 0m
                        },
                        new
                        {
                            ReservationID = 2,
                            CustomerAddress = "Stationlaan 1",
                            CustomerEmail = "alice@example.com",
                            CustomerName = "Alice",
                            CustomerPhone = "0400000000",
                            TotalPrice = 0m
                        });
                });

            modelBuilder.Entity("Laptopreservation.Models.ReservationItem", b =>
                {
                    b.Property<int>("ReservationItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReservationItemID"));

                    b.Property<int>("LaptopID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ReservationItemID");

                    b.HasIndex("LaptopID");

                    b.HasIndex("ReservationID");

                    b.ToTable("ReservationItems");

                    b.HasData(
                        new
                        {
                            ReservationItemID = 1,
                            LaptopID = 1,
                            Quantity = 1,
                            ReservationID = 1,
                            UnitPrice = 20.05m
                        },
                        new
                        {
                            ReservationItemID = 2,
                            LaptopID = 2,
                            Quantity = 2,
                            ReservationID = 1,
                            UnitPrice = 20000m
                        },
                        new
                        {
                            ReservationItemID = 3,
                            LaptopID = 2,
                            Quantity = 1,
                            ReservationID = 2,
                            UnitPrice = 20000m
                        });
                });

            modelBuilder.Entity("Laptopreservation.Models.ReservationItem", b =>
                {
                    b.HasOne("Laptopreservation.Models.Laptop", "Laptop")
                        .WithMany()
                        .HasForeignKey("LaptopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Laptopreservation.Models.Reservation", "Reservation")
                        .WithMany("Items")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Laptop");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Laptopreservation.Models.Reservation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
